name: publish-to-npm
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The updated registry version number'
        required: true
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          scope: @hizmailovich
      - name: Configure Git
        run: |
          git config user.email ${{ secrets.EMAIL }}
          git config user.name ${{ secrets.USERNAME }}
      - name: Install Yarn
        run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: git stash
      - run: npm version ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }} 📣"
      - run: git push
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
          scope: @hizmailovich
      - name: Authenticate with the GitHub Package Registry
        run:
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >
          ~/.npmrc
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}